// Generated by docs:routes; edit the corresponding docs page metadata.
export const docsNavigation = [
  {
    slug: "accordion",
    label: "Accordion",
    group: "components",
  },
  {
    slug: "motion-accordion",
    label: "Accordion",
    group: "motion",
  },
  {
    slug: "alert",
    label: "Alert",
    group: "components",
  },
  {
    slug: "alert-dialog",
    label: "Alert Dialog",
    group: "components",
  },
  {
    slug: "motion-alert-dialog",
    label: "Alert Dialog",
    group: "motion",
  },
  {
    slug: "aspect-ratio",
    label: "Aspect Ratio",
    group: "components",
  },
  {
    slug: "avatar",
    label: "Avatar",
    group: "components",
  },
  {
    slug: "badge",
    label: "Badge",
    group: "components",
  },
  {
    slug: "breadcrumb",
    label: "Breadcrumb",
    group: "components",
  },
  {
    slug: "button",
    label: "Button",
    group: "components",
  },
  {
    slug: "button-group",
    label: "Button Group",
    group: "components",
  },
  {
    slug: "calendar",
    label: "Calendar",
    group: "components",
  },
  {
    slug: "card",
    label: "Card",
    group: "components",
  },
  {
    slug: "carousel",
    label: "Carousel",
    group: "components",
  },
  {
    slug: "chart",
    label: "Chart",
    group: "components",
  },
  {
    slug: "checkbox",
    label: "Checkbox",
    group: "components",
  },
  {
    slug: "cn",
    label: "cn Utility",
    group: "components",
  },
  {
    slug: "collapsible",
    label: "Collapsible",
    group: "components",
  },
  {
    slug: "motion-collapsible",
    label: "Collapsible",
    group: "motion",
  },
  {
    slug: "combobox",
    label: "Combobox",
    group: "components",
  },
  {
    slug: "command",
    label: "Command",
    group: "components",
  },
  {
    slug: "context-menu",
    label: "Context Menu",
    group: "components",
  },
  {
    slug: "data-table",
    label: "Data Table",
    group: "components",
  },
  {
    slug: "date-picker",
    label: "Date Picker",
    group: "components",
  },
  {
    slug: "dialog",
    label: "Dialog",
    group: "components",
  },
  {
    slug: "motion-dialog",
    label: "Dialog",
    group: "motion",
  },
  {
    slug: "direction",
    label: "Direction",
    group: "components",
  },
  {
    slug: "drawer",
    label: "Drawer",
    group: "components",
  },
  {
    slug: "dropdown",
    label: "Dropdown",
    group: "components",
  },
  {
    slug: "dropzone",
    label: "Dropzone",
    group: "components",
  },
  {
    slug: "empty",
    label: "Empty",
    group: "components",
  },
  {
    slug: "field",
    label: "Field",
    group: "components",
  },
  {
    slug: "formisch",
    label: "Formisch",
    group: "forms",
  },
  {
    slug: "hooks-package",
    label: "Hooks",
    group: "packages",
  },
  {
    slug: "hover-card",
    label: "Hover Card",
    group: "components",
  },
  {
    slug: "i18n-package",
    label: "i18n",
    group: "packages",
  },
  {
    slug: "icons-package",
    label: "Icons",
    group: "packages",
  },
  {
    slug: "image",
    label: "Image",
    group: "components",
  },
  {
    slug: "input",
    label: "Input",
    group: "components",
  },
  {
    slug: "input-group",
    label: "Input Group",
    group: "components",
  },
  {
    slug: "input-otp",
    label: "Input OTP",
    group: "components",
  },
  {
    slug: "item",
    label: "Item",
    group: "components",
  },
  {
    slug: "kbd",
    label: "Kbd",
    group: "components",
  },
  {
    slug: "label",
    label: "Label",
    group: "components",
  },
  {
    slug: "locale-segment-group",
    label: "Locale Segment Group",
    group: "components",
  },
  {
    slug: "menubar",
    label: "Menubar",
    group: "components",
  },
  {
    slug: "native-select",
    label: "Native Select",
    group: "components",
  },
  {
    slug: "navigation-menu",
    label: "Navigation Menu",
    group: "components",
  },
  {
    slug: "pagination",
    label: "Pagination",
    group: "components",
  },
  {
    slug: "popover",
    label: "Popover",
    group: "components",
  },
  {
    slug: "progress",
    label: "Progress",
    group: "components",
  },
  {
    slug: "prose",
    label: "Prose",
    group: "components",
  },
  {
    slug: "radio-group",
    label: "Radio Group",
    group: "components",
  },
  {
    slug: "scroll-area",
    label: "Scroll Area",
    group: "components",
  },
  {
    slug: "select",
    label: "Select",
    group: "components",
  },
  {
    slug: "selectable-card",
    label: "Selectable Card",
    group: "components",
  },
  {
    slug: "separator",
    label: "Separator",
    group: "components",
  },
  {
    slug: "motion-sheet",
    label: "Sheet",
    group: "motion",
  },
  {
    slug: "sheet",
    label: "Sheet",
    group: "components",
  },
  {
    slug: "sidebar",
    label: "Sidebar",
    group: "components",
  },
  {
    slug: "signals-package",
    label: "Signals",
    group: "packages",
  },
  {
    slug: "skeleton",
    label: "Skeleton",
    group: "components",
  },
  {
    slug: "slider",
    label: "Slider",
    group: "components",
  },
  {
    slug: "sonner",
    label: "Sonner",
    group: "components",
  },
  {
    slug: "spinner",
    label: "Spinner",
    group: "components",
  },
  {
    slug: "state-package",
    label: "State",
    group: "packages",
  },
  {
    slug: "switch",
    label: "Switch",
    group: "components",
  },
  {
    slug: "table",
    label: "Table",
    group: "components",
  },
  {
    slug: "motion-tabs",
    label: "Tabs",
    group: "motion",
  },
  {
    slug: "tabs",
    label: "Tabs",
    group: "components",
  },
  {
    slug: "textarea",
    label: "Textarea",
    group: "components",
  },
  {
    slug: "theme-toggle",
    label: "Theme Toggle",
    group: "components",
  },
  {
    slug: "theming",
    label: "Theming",
    group: "components",
  },
  {
    slug: "toast",
    label: "Toast",
    group: "components",
  },
  {
    slug: "toggle",
    label: "Toggle",
    group: "components",
  },
  {
    slug: "toggle-group",
    label: "Toggle Group",
    group: "components",
  },
  {
    slug: "tooltip",
    label: "Tooltip",
    group: "components",
  },
  {
    slug: "tree",
    label: "Tree",
    group: "components",
  },
  {
    slug: "type-definition",
    label: "Type Definition",
    group: "components",
  },
  {
    slug: "typography",
    label: "Typography",
    group: "components",
  },
  {
    slug: "ui-motion",
    label: "UI Motion",
    group: "components",
  },
  {
    slug: "video",
    label: "Video",
    group: "components",
  },
] as const;
