export const docsRouteManifest = [
  {
    slug: "accordion",
    sections: [
      "installation",
      "usage",
      "basic",
      "multiple",
      "disabled",
      "borders",
      "card",
      "rtl",
      "with-motion",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "alert",
    sections: [
      "installation",
      "usage",
      "basic",
      "destructive",
      "action",
      "colors",
      "rtl",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "alert-dialog",
    sections: [
      "installation",
      "usage",
      "basic",
      "small",
      "media",
      "small-media",
      "destructive",
      "rtl",
      "with-motion",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "aspect-ratio",
    sections: [
      "installation",
      "usage",
      "demo",
      "square",
      "portrait",
      "rtl",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "avatar",
    sections: [
      "installation",
      "usage",
      "basic",
      "badge",
      "badge-icon",
      "group",
      "group-count",
      "group-count-icon",
      "sizes",
      "dropdown",
      "rtl",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "badge",
    sections: [
      "installation",
      "usage",
      "variants",
      "with-icon",
      "with-spinner",
      "link",
      "custom-colors",
      "sizes",
      "rtl",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "breadcrumb",
    sections: [
      "installation",
      "usage",
      "custom-separator",
      "dropdown",
      "collapsed",
      "link-component",
      "rtl",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "button",
    sections: [
      "installation",
      "usage",
      "cursor",
      "size",
      "default",
      "outline",
      "secondary",
      "inverse",
      "ghost",
      "destructive",
      "link",
      "icon",
      "with-icon",
      "rounded",
      "spinner",
      "button-group",
      "as-child",
      "rtl",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "button-group",
    sections: [
      "installation",
      "usage",
      "accessibility",
      "toggle-group",
      "group-text",
      "orientation",
      "size",
      "nested",
      "separator",
      "split",
      "input",
      "input-group",
      "dropdown",
      "select",
      "popover",
      "rtl",
      "api-reference",
    ],
  },
  {
    slug: "calendar",
    sections: [
      "installation",
      "usage",
      "demo",
      "timezone",
      "basic",
      "range-calendar",
      "month-year-selector",
      "presets",
      "date-time-picker",
      "booked-dates",
      "custom-cell-size",
      "week-numbers",
      "rtl",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "card",
    sections: [
      "installation",
      "usage",
      "card-demo",
      "card-size",
      "card-image",
      "card-rtl",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "carousel",
    sections: [
      "installation",
      "usage",
      "carousel-demo",
      "carousel-sizes",
      "carousel-spacing",
      "carousel-orientation",
      "carousel-opts",
      "carousel-api",
      "carousel-autoplay",
      "carousel-rtl",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "chart",
    sections: [
      "installation",
      "usage",
      "line-chart",
      "bar-chart",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "checkbox",
    sections: [
      "installation",
      "usage",
      "1",
      "2",
      "3",
      "4",
      "checkbox-demo",
      "checkbox-usage",
      "checkbox-controlled",
      "checkbox-indeterminate",
      "checkbox-invalid",
      "checkbox-basic",
      "checkbox-description",
      "checkbox-disabled",
      "checkbox-group",
      "checkbox-table",
      "checkbox-rtl",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "cn",
    sections: [
      "installation",
      "usage",
      "basic-classes",
      "conditional-classes",
      "arrays-and-objects",
      "override-defaults",
      "preact-component",
      "variant-system",
      "clsx-vs-cn",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "collapsible",
    sections: [
      "installation",
      "usage",
      "collapsible-demo",
      "collapsible-usage",
      "collapsible-controlled",
      "collapsible-basic",
      "collapsible-settings",
      "collapsible-file-tree",
      "collapsible-rtl",
      "with-motion",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "combobox",
    sections: [
      "installation",
      "usage",
      "basic",
      "preset-select",
      "controlled",
      "popup-button",
      "custom-items",
      "groups",
      "invalid",
      "disabled",
      "auto-highlight",
      "clear-button",
      "inline-input",
      "multi-chips",
      "rtl",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "command",
    sections: [
      "installation",
      "usage",
      "demo-inline",
      "dialog-basic",
      "dialog-shortcuts",
      "dialog-groups",
      "dialog-scrollable",
      "rtl",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "context-menu",
    sections: [
      "installation",
      "usage",
      "full-demo",
      "basic-example",
      "submenu-example",
      "shortcuts-example",
      "groups-example",
      "icons-example",
      "checkboxes-example",
      "radio-example",
      "destructive-example",
      "rtl-example",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "data-table",
    sections: [
      "installation",
      "usage",
      "full-demo",
      "basic-table",
      "empty-state",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "date-picker",
    sections: [
      "installation",
      "usage",
      "demo-composed",
      "date-picker-convenience",
      "calendar-icon-composed",
      "basic-field",
      "range-picker",
      "date-of-birth",
      "input-picker",
      "time-picker",
      "natural-language",
      "rtl",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "dialog",
    sections: [
      "installation",
      "usage",
      "presentation-slot",
      "dialog-demo",
      "basic-dialog",
      "custom-close",
      "no-close-button",
      "sticky-footer",
      "scrollable-content",
      "dialog-rtl",
      "dialog-actions",
      "with-motion",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "direction",
    sections: [
      "installation",
      "usage",
      "card-rtl",
      "direction-provider",
      "direction-legacy",
      "hook-usage",
      "html-note",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "drawer",
    sections: [
      "installation",
      "usage",
      "drawer-demo",
      "basic-example",
      "footer-actions",
      "scrollable",
      "sides",
      "responsive-dialog",
      "rtl-drawer",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "dropdown",
    sections: [
      "installation",
      "usage",
      "basic-dropdown",
      "as-child",
      "grouped-shortcuts-icons",
      "submenu",
      "checkbox-items",
      "radio-items",
      "positioning",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "dropzone",
    sections: [
      "installation",
      "usage",
      "basic-dropzone",
      "dropzone-indicators",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "empty",
    sections: [
      "installation",
      "usage",
      "empty-demo",
      "empty-usage",
      "empty-legacy",
      "empty-legacy-action",
      "empty-outline",
      "empty-background",
      "empty-avatar",
      "empty-avatar-group",
      "empty-input-group",
      "empty-rtl",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "field",
    sections: [
      "installation",
      "usage",
      "field-anatomy",
      "field-legacy",
      "field-input",
      "field-textarea",
      "field-select",
      "field-slider",
      "field-fieldset",
      "field-checkbox",
      "field-radio",
      "field-switch",
      "field-choice-card",
      "field-group-sep",
      "field-error-array",
      "field-responsive",
      "field-rtl",
      "field-legacy-error",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "formisch",
    sections: [
      "installation",
      "usage",
      "demo",
      "approach",
      "form-methods",
      "api-reference",
      "anatomy",
      "schema-and-setup",
      "validation",
      "validation-modes",
      "displaying-errors",
      "input",
      "textarea",
      "select",
      "checkbox",
      "radio-group",
      "switch",
      "complex-forms",
      "resetting-form",
      "array-fields",
      "accessibility",
      "sources",
    ],
  },
  {
    slug: "hooks-package",
    sections: ["installation", "usage", "api-reference", "accessibility"],
  },
  {
    slug: "hover-card",
    sections: [
      "installation",
      "usage",
      "hover-demo",
      "hover-usage",
      "hover-delays",
      "hover-positioning",
      "hover-sides",
      "hover-rtl",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "i18n-package",
    sections: ["installation", "usage", "api-reference", "accessibility"],
  },
  {
    slug: "icons-package",
    sections: ["installation", "usage", "api-reference", "accessibility"],
  },
  {
    slug: "image",
    sections: [
      "installation",
      "usage",
      "basic-image",
      "image-thumbnail",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "input",
    sections: [
      "installation",
      "usage",
      "input-demo",
      "input-basic",
      "input-field",
      "input-field-group",
      "input-disabled",
      "input-invalid",
      "input-file",
      "input-inline",
      "input-grid",
      "input-required",
      "input-badge",
      "input-input-group",
      "input-button-group",
      "input-form",
      "input-sizes",
      "input-rtl",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "input-group",
    sections: [
      "installation",
      "usage",
      "ig-demo",
      "ig-usage",
      "url-input-group",
      "username-input-group",
      "ig-inline-start",
      "ig-inline-end",
      "ig-block-start",
      "ig-block-end",
      "ig-icons",
      "ig-text",
      "ig-button",
      "ig-kbd",
      "ig-dropdown",
      "ig-spinner",
      "ig-textarea-code",
      "ig-rtl",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "input-otp",
    sections: [
      "installation",
      "usage",
      "otp-demo",
      "otp-usage",
      "otp-pattern",
      "otp-separator-multi",
      "otp-disabled",
      "otp-controlled",
      "otp-invalid",
      "otp-four",
      "otp-alphanumeric",
      "otp-form",
      "otp-rtl",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "item",
    sections: [
      "installation",
      "usage",
      "item-demo",
      "item-usage",
      "item-variants",
      "item-sizes",
      "item-icon",
      "item-avatar",
      "item-image",
      "item-group",
      "item-header-footer",
      "item-link",
      "item-separator",
      "item-dropdown",
      "item-rtl",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "kbd",
    sections: [
      "installation",
      "usage",
      "kbd-demo",
      "kbd-usage",
      "kbd-group",
      "kbd-button",
      "kbd-tooltip",
      "kbd-input-group",
      "kbd-sizes",
      "kbd-rtl",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "label",
    sections: [
      "installation",
      "usage",
      "label-demo",
      "label-usage",
      "label-with-checkbox",
      "label-with-input",
      "label-with-textarea",
      "label-field-hint",
      "label-sizes",
      "label-rtl",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "locale-segment-group",
    sections: [
      "installation",
      "usage",
      "basic-locale-segment-group",
      "custom-options",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "menubar",
    sections: [
      "installation",
      "usage",
      "demo",
      "minimal",
      "checkbox",
      "radio",
      "submenu",
      "icons",
      "rtl",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "motion-accordion",
    sections: ["installation", "usage", "basic", "api-reference", "accessibility"],
  },
  {
    slug: "motion-alert-dialog",
    sections: ["installation", "usage", "basic", "api-reference", "accessibility"],
  },
  {
    slug: "motion-collapsible",
    sections: ["installation", "usage", "basic", "api-reference", "accessibility"],
  },
  {
    slug: "motion-dialog",
    sections: ["installation", "usage", "basic", "api-reference", "accessibility"],
  },
  {
    slug: "motion-sheet",
    sections: ["installation", "usage", "basic", "side", "api-reference", "accessibility"],
  },
  {
    slug: "motion-tabs",
    sections: ["installation", "usage", "basic", "api-reference", "accessibility"],
  },
  {
    slug: "native-select",
    sections: [
      "installation",
      "usage",
      "native-select-default",
      "native-select-groups",
      "native-select-disabled",
      "native-select-invalid",
      "native-select-size",
      "native-select-vs-select",
      "native-select-rtl",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "navigation-menu",
    sections: [
      "installation",
      "usage",
      "demo",
      "basic",
      "link-as-trigger-style",
      "rtl",
      "delays",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "pagination",
    sections: [
      "installation",
      "usage",
      "pagination-demo",
      "pagination-simple",
      "pagination-icons-only",
      "pagination-rtl",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "popover",
    sections: [
      "installation",
      "usage",
      "basic-popover",
      "popover-form",
      "popover-placement",
      "popover-alignment",
      "popover-form-compact",
      "popover-rtl",
      "popover-close",
      "popover-default-open",
      "popover-settings",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "progress",
    sections: [
      "installation",
      "usage",
      "basic-progress",
      "progress-with-label",
      "controlled-progress",
      "progress-indeterminate",
      "custom-max",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "prose",
    sections: [
      "installation",
      "usage",
      "article-prose",
      "narrow-prose",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "radio-group",
    sections: [
      "installation",
      "usage",
      "radio-default-labels",
      "radio-description",
      "radio-choice-card",
      "radio-fieldset-field",
      "radio-disabled-invalid",
      "radio-inline-sm",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "scroll-area",
    sections: [
      "installation",
      "usage",
      "vertical-feed",
      "horizontal-gallery",
      "reading-container",
      "compact-chips",
      "both-axes",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "select",
    sections: [
      "installation",
      "usage",
      "basic-select",
      "select-groups",
      "select-disabled",
      "select-scrollable",
      "select-invalid",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "selectable-card",
    sections: [
      "installation",
      "usage",
      "selectable-card-demo",
      "selectable-card-disabled",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "separator",
    sections: [
      "installation",
      "usage",
      "horizontal-separator",
      "vertical-separator",
      "menu-separator",
      "list-separator",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "sheet",
    sections: [
      "installation",
      "usage",
      "basic-sheet",
      "sheet-side",
      "sheet-no-close-button",
      "with-motion",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "sidebar",
    sections: [
      "installation",
      "usage",
      "basic-sidebar",
      "sidebar-with-inset",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "signals-package",
    sections: ["installation", "usage", "api-reference", "accessibility"],
  },
  {
    slug: "skeleton",
    sections: [
      "installation",
      "usage",
      "pulse-skeleton",
      "shimmer-skeleton",
      "glass-skeleton",
      "avatar-skeleton",
      "text-skeleton",
      "card-skeleton",
      "form-skeleton",
      "table-skeleton",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "slider",
    sections: [
      "installation",
      "usage",
      "basic-slider",
      "range-slider",
      "multiple-thumbs",
      "stepped-slider",
      "controlled-slider",
      "controlled-range-slider",
      "disabled-slider",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "sonner",
    sections: [
      "installation",
      "usage",
      "basic-toast",
      "dismissible-toast",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "spinner",
    sections: [
      "installation",
      "usage",
      "basic-spinner",
      "spinner-sizes",
      "spinner-tones",
      "spinner-in-buttons",
      "spinner-loading-surface",
      "spinner-overlay",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "state-package",
    sections: ["installation", "usage", "api-reference", "accessibility"],
  },
  {
    slug: "switch",
    sections: [
      "installation",
      "usage",
      "switch-description",
      "switch-choice-card",
      "switch-disabled-invalid",
      "switch-size",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "table",
    sections: [
      "installation",
      "usage",
      "invoice-table",
      "table-footer",
      "table-actions",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "tabs",
    sections: [
      "installation",
      "usage",
      "synced-tabs",
      "disabled-triggers",
      "nested-tabs",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "textarea",
    sections: [
      "installation",
      "usage",
      "basic-textarea",
      "textarea-field",
      "textarea-disabled-invalid",
      "textarea-sizes",
      "textarea-counter",
      "textarea-autoresize",
      "textarea-production-field",
      "textarea-with-action",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "theme-toggle",
    sections: [
      "installation",
      "usage",
      "basic-theme-toggle",
      "custom-toggle-label",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "theming",
    sections: [
      "installation",
      "usage",
      "css-setup",
      "provider-controls",
      "token-overrides",
      "tailwind-preset",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "toast",
    sections: [
      "installation",
      "usage",
      "basic-toast",
      "toast-dismiss",
      "toast-types",
      "toast-position",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "toggle",
    sections: [
      "installation",
      "usage",
      "basic-toggle",
      "toggle-options",
      "variants-and-sizes",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "toggle-group",
    sections: [
      "installation",
      "usage",
      "single-selection",
      "sizes",
      "spacing",
      "vertical",
      "disabled",
      "custom-font-weight",
      "icon-only",
      "multi-selection",
      "pill-style",
      "controlled",
      "rtl",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "tooltip",
    sections: [
      "installation",
      "usage",
      "basic-tooltip",
      "side-tooltip",
      "align-tooltip",
      "provider-delay-tooltip",
      "non-hoverable-content-tooltip",
      "shortcut-tooltip",
      "disabled-button-tooltip",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "tree",
    sections: [
      "installation",
      "usage",
      "basic",
      "default-expanded",
      "controlled-expansion",
      "single-selection",
      "multiple-selection",
      "no-icons-lines",
      "variants",
      "disabled",
      "deep",
      "rtl",
      "accessibility",
      "keyboard",
      "api-reference",
    ],
  },
  {
    slug: "typography",
    sections: [
      "installation",
      "usage",
      "full-example",
      "h1",
      "h2",
      "h3",
      "h4",
      "paragraph",
      "blockquote",
      "table",
      "list",
      "inline-code",
      "lead",
      "large",
      "small",
      "muted",
      "rtl-support",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "ui-motion",
    sections: [
      "installation",
      "usage",
      "dialog",
      "alert-dialog",
      "sheet",
      "accordion",
      "collapsible",
      "reduced-motion",
      "api-reference",
      "accessibility",
    ],
  },
  {
    slug: "video",
    sections: [
      "installation",
      "usage",
      "video-with-source",
      "muted-preview",
      "api-reference",
      "accessibility",
    ],
  },
] as const;
