import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/shared/index.ts",
    "src/sidebar/index.ts",
    "src/login/index.ts",
    "src/signup/index.ts",
    "src/login/login-01/index.ts",
    "src/login/login-02/index.ts",
    "src/login/login-03/index.ts",
    "src/login/login-04/index.ts",
    "src/login/login-05/index.ts",
    "src/signup/signup-01/index.ts",
    "src/signup/signup-02/index.ts",
    "src/signup/signup-03/index.ts",
    "src/signup/signup-04/index.ts",
    "src/signup/signup-05/index.ts",
    "src/auth/index.ts",
    "src/auth/auth-mfa/index.ts",
    "src/auth/auth-password-reset/index.ts",
    "src/auth/auth-sign-in/index.ts",
    "src/auth/auth-sign-up/index.ts",
    "src/auth/login-01/index.ts",
    "src/auth/login-02/index.ts",
    "src/auth/register-01/index.ts",
    "src/app-sidebar/index.ts",
    "src/app-sidebar/sidebar-01/index.ts",
    "src/app-sidebar/sidebar-02/index.ts",
    "src/app-sidebar/sidebar-03/index.ts",
    "src/app-sidebar/sidebar-04/index.ts",
    "src/app-sidebar/sidebar-05/index.ts",
    "src/app-sidebar/sidebar-06/index.ts",
    "src/app-sidebar/sidebar-07/index.ts",
    "src/dashboard/index.ts",
    "src/dashboard/analytics-overview/index.ts",
    "src/dashboard/dashboard-layout/index.ts",
    "src/dashboard/command-palette/index.ts",
    "src/dashboard/conversion-funnel/index.ts",
    "src/dashboard/cost-breakdown/index.ts",
    "src/dashboard/event-calendar/index.ts",
    "src/dashboard/event-list/index.ts",
    "src/dashboard/kanban-board/index.ts",
    "src/dashboard/metrics-grid/index.ts",
    "src/dashboard/notifications-popover/index.ts",
    "src/dashboard/profile-menu/index.ts",
    "src/dashboard/progress-breakdown/index.ts",
    "src/dashboard/quick-actions/index.ts",
    "src/dashboard/theme-customize/index.ts",
    "src/dashboard/toggle-setting-list/index.ts",
    "src/communication/index.ts",
    "src/communication/chat-thread/index.ts",
    "src/communication/chat-two-pane/index.ts",
    "src/communication/inbox/index.ts",
    "src/communication/ai-llm-chat/index.ts",
    "src/commerce/index.ts",
    "src/commerce/payment-form/index.ts",
    "src/commerce/saved-cards-list/index.ts",
    "src/commerce/checkout-flow/index.ts",
    "src/marketing/index.ts",
    "src/marketing/bento-01/index.ts",
    "src/marketing/contact-01/index.ts",
    "src/marketing/contact-us/index.ts",
    "src/marketing/cta-01/index.ts",
    "src/marketing/faq-01/index.ts",
    "src/marketing/features-01/index.ts",
    "src/marketing/footer-01/index.ts",
    "src/marketing/header-01/index.ts",
    "src/marketing/hero-01/index.ts",
    "src/marketing/logos-01/index.ts",
    "src/marketing/logos-02/index.ts",
    "src/marketing/logos-03/index.ts",
    "src/marketing/pricing-01/index.ts",
    "src/marketing/testimonials-01/index.ts",
  ],
  format: ["esm"],
  dts: true,
  sourcemap: true,
  clean: true,
  external: [
    "preact",
    "preact/hooks",
    "@preact/signals",
    "@kamod-ch/ui",
    "@kamod-ch/icons",
    "@kamod-ch/themes",
  ],
});
