import type { AccessibilityProfile } from "./types";

export const formischAccessibility: AccessibilityProfile = {
  foundation:
    "Formisch manages typed field state and validation through a store; Kamod provides the rendered controls and field layout. In the Preact adapter, `field.input` and `field.errors` are signals, so read their `.value` when choosing displayed values or messages. Neither a schema nor a red field wrapper automatically supplies an accessible name, an error-description relationship or an appropriate focus destination. The examples use explicit IDs and labels; review each control's rendered HTML when adapting them. Preserve `field.props` for native inputs, and use the demonstrated value/change binding for composite controls rather than assuming every component accepts the same event contract.",
  naming:
    "Give every input a visible `FieldLabel` whose `htmlFor` matches the real input or labelable trigger ID. Use `useId` or an instance-specific prefix so repeated forms do not compete for the same label. Add IDs to persistent help text and FieldError, then reference the applicable IDs with `aria-describedby` on the actual control. Keep instructions available before submission and make corrections specific: Enter a valid email address is more useful than Invalid input. For grouped choices, use FieldSet/FieldLegend and individual option labels; a group question is not a replacement for each option's name. Put `required`, `disabled` and `aria-invalid` on controls where appropriate, not only on the visual Field wrapper.",
  interaction:
    "Choose validation timing deliberately. A submit-first flow lets someone complete a field before being shown an error; revalidation on input can then help them correct it. After an unsuccessful submission, verify where Formisch's focus behavior lands for native inputs and for custom triggers; do not add a competing focus effect blindly. For a long form, consider a focused error summary with links to affected controls when inline feedback alone leaves errors hard to find. Do not move focus after each keystroke. In FieldArray, key rows by the stable IDs in `array.items.value` while using the current index for the field path. After adding or removing a row, choose an appropriate surviving field or Add action, and ensure each removal button identifies its row.",
  pitfalls:
    "Treat schema errors, server-rejected values and network failures as distinct outcomes. Preserve entered data after a rejected request and give a visible retry path. During submission, show meaningful pending text and prevent duplicate requests without stranding focus on a removed button. A disabled button alone does not explain progress. FieldError already has alert semantics; avoid wrapping every error in another assertive live region or repeatedly announcing the same message from both a summary and each field. Keep success visible near the form when the task stays on the page. When resetting, clear any application-owned request/result state deliberately as well as resetting the form store, and explain destructive resets when they would discard substantial work.",
  checks: [
    "Submit an untouched form, correct one error at a time, then submit valid data. Verify label, required state, help text and error text for both native fields and custom select/switch triggers with a screen reader.",
    "Add several array rows, remove the middle row and reorder if supported. Confirm stable input identity, unique IDs, correct remaining values and a sensible focus destination after the focused row disappears.",
    "Simulate slow submission, server validation failure, network rejection, retry and reset. Keep values recoverable, feedback understandable and all actions reachable at narrow widths, enlarged text and in both themes.",
  ],
  example: {
    title: "Connect the Visible Error to the Real Input",
    note: "This is a fragment for an existing FormischField render callback, not a standalone form. Your store must include a string email field; define a unique id in the owning component. Preserve the native handlers while adding explicit label/error relationships.",
    code: 'import { Field, FieldLabel, FieldError, Input } from "@kamod-ch/ui";\n\n// Inside your existing typed FormischField render callback:\n// field is supplied by <FormischField of={form} path={["email"]}>.\nconst invalid = Boolean(field.errors.value?.length);\nconst helpId = `${id}-help`;\nconst errorId = `${id}-error`;\n\nreturn (\n  <Field invalid={invalid}>\n    <FieldLabel htmlFor={id}>Email address</FieldLabel>\n    <Input {...field.props} id={id} type="email" autoComplete="email"\n      value={typeof field.input.value === "string" ? field.input.value : ""}\n      aria-invalid={invalid || undefined}\n      aria-describedby={[helpId, invalid ? errorId : undefined].filter(Boolean).join(" ")} />\n    <p id={helpId}>Use an address where you can receive account updates.</p>\n    {invalid && <FieldError id={errorId}\n      errors={field.errors.value?.map((message) => ({ message }))} />}\n  </Field>\n);',
  },
};
