import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    "dialog/index": "src/dialog/index.ts",
    "alert-dialog/index": "src/alert-dialog/index.ts",
    "sheet/index": "src/sheet/index.ts",
    "accordion/index": "src/accordion/index.ts",
    "collapsible/index": "src/collapsible/index.ts",
    "tabs/index": "src/tabs/index.ts",
  },
  format: ["esm"],
  dts: true,
  sourcemap: true,
  clean: true,
  splitting: true,
  treeshake: true,
  target: "esnext",
  external: [
    "preact",
    "preact/hooks",
    "preact/jsx-runtime",
    "preact/compat",
    "@preact/signals",
    "@kamod-ch/ui",
    "@kamod-ch/ui/dialog",
    "@kamod-ch/ui/sheet",
    "@kamod-ch/ui/accordion",
    "@kamod-ch/ui/collapsible",
    "@kamod-ch/ui/tabs",
    "@kamod-ch/ui/lib/utils",
    "@kamod-ch/ui/lib/interactive",
    "@kamod-ch/motion",
    "@kamod-ch/motion/motion",
    "@kamod-ch/motion/presence",
    "@kamod-ch/motion/presets",
    "motion",
    "motion/mini",
  ],
});
