import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    "library/index": "src/library/index.ts",
    "presets/basic": "src/presets/basic.ts",
    "presets/forms": "src/presets/forms.ts",
    "prompts/index": "src/prompts/index.ts",
    "examples/fixtures": "src/examples/fixtures.ts",
  },
  format: ["esm"],
  dts: true,
  sourcemap: true,
  clean: true,
  splitting: true,
  treeshake: true,
  target: "esnext",
  external: [
    "preact",
    "preact/hooks",
    "preact/jsx-runtime",
    "preact/compat",
    "@preact/signals",
    "@kamod-ch/ui",
    "@kamod-ch/ui/lib/utils",
    "@kamod-ch/ui/button",
    "@kamod-ch/ui/card",
    "@kamod-ch/ui/typography",
    "@kamod-ch/ui/separator",
    "@kamod-ch/ui/alert",
    "@kamod-ch/ui/badge",
    "@kamod-ch/ui/progress",
    "@kamod-ch/ui/skeleton",
    "@kamod-ch/ui/tabs",
    "@kamod-ch/ui/accordion",
    "@kamod-ch/ui/field",
    "@kamod-ch/ui/input",
    "@kamod-ch/ui/textarea",
    "@kamod-ch/ui/native-select",
    "@kamod-ch/ui/checkbox",
    "@kamod-ch/ui/switch",
    "@openuidev/react-lang",
    "zod",
    "react",
    "react-dom",
    "react/jsx-runtime",
  ],
});
