import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    "library/index": "src/library/index.ts",
    "presets/basic": "src/presets/basic.ts",
    "presets/forms": "src/presets/forms.ts",
    "presets/dashboard": "src/presets/dashboard.ts",
    "prompts/index": "src/prompts/index.ts",
    "examples/fixtures": "src/examples/fixtures.ts",
    "demo/index": "src/demo/index.ts",
  },
  format: ["esm"],
  dts: true,
  sourcemap: true,
  clean: true,
  splitting: true,
  treeshake: true,
  target: "esnext",
  external: [
    "preact",
    "preact/hooks",
    "preact/jsx-runtime",
    "preact/compat",
    "@preact/signals",
    "@kamod-ch/ui",
    "@kamod-ch/ui/lib/utils",
    "@kamod-ch/ui/button",
    "@kamod-ch/ui/card",
    "@kamod-ch/ui/typography",
    "@kamod-ch/ui/separator",
    "@kamod-ch/ui/alert",
    "@kamod-ch/ui/badge",
    "@kamod-ch/ui/progress",
    "@kamod-ch/ui/skeleton",
    "@kamod-ch/ui/tabs",
    "@kamod-ch/ui/accordion",
    "@kamod-ch/ui/field",
    "@kamod-ch/ui/input",
    "@kamod-ch/ui/textarea",
    "@kamod-ch/ui/native-select",
    "@kamod-ch/ui/checkbox",
    "@kamod-ch/ui/switch",
    "@kamod-ch/ui/radio-group",
    "@kamod-ch/ui/collapsible",
    "@kamod-ch/ui/empty",
    "@kamod-ch/ui/avatar",
    "@kamod-ch/ui/label",
    "@kamod-ch/ui/spinner",
    "@kamod-ch/ui/tooltip",
    "@kamod-ch/ui/dialog",
    "@kamod-ch/ui/alert-dialog",
    "@kamod-ch/ui/date-picker",
    "@kamod-ch/ui/combobox",
    "@kamod-ch/ui/select",
    "@kamod-ch/ui/slider",
    "@kamod-ch/ui/table",
    "@kamod-ch/ui/data-table",
    "@kamod-ch/ui/pagination",
    "@kamod-ch/ui/breadcrumb",
    "@kamod-ch/ui/popover",
    "@kamod-ch/ui/hover-card",
    "@kamod-ch/ui/dropdown",
    "@kamod-ch/ui/drawer",
    "@kamod-ch/ui/sheet",
    "@kamod-ch/ui/scroll-area",
    "@kamod-ch/ui/image",
    "@kamod-ch/ui/video",
    "@kamod-ch/ui/input-otp",
    "@kamod-ch/ui/input-group",
    "@kamod-ch/ui/selectable-card",
    "@kamod-ch/ui/item",
    "@kamod-ch/ui/button-group",
    "@kamod-ch/ui/toggle",
    "@kamod-ch/ui/toggle-group",
    "@kamod-ch/ui/command",
    "@kamod-ch/ui/calendar",
    "@kamod-ch/ui/chart",
    "@kamod-ch/ui/toast",
    "@kamod-ch/ui/sonner",
    "@kamod-ch/ui/sidebar",
    "@kamod-ch/ui/navigation-menu",
    "@kamod-ch/ui/menubar",
    "@kamod-ch/ui/context-menu",
    "@kamod-ch/ui/aspect-ratio",
    "@kamod-ch/ui/prose",
    "@kamod-ch/ui/theme-toggle",
    "@kamod-ch/ui/kbd",
    "@kamod-ch/ui/locale-segment-group",
    "@openuidev/react-lang",
    "zod",
    "react",
    "react-dom",
    "react/jsx-runtime",
  ],
});
