name: Build and Deploy Preact to All-Inkl

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Checkout Code
        uses: actions/checkout@v4

      - name: 📌 Setup pnpm
        uses: pnpm/action-setup@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🏗️ Build Preact App
        run: pnpm run build

      - name: 📂 Sync Dist to Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./apps/demo/dist/
          server-dir: /www/htdocs/w014120b/ui.kamod.ch/
          delete-remote-files: true
          # Only add this if you experience timeout issues
          # port: 21